const types = {
  SET_THEME: 'SET_THEME',
  SET_CHARACTERS: 'SET_CHARACTERS',
  SET_FAVORITE: 'SET_FAVORITE',
  REMOVE_FAVORITE: 'REMOVE_FAVORITE',
  SET_SEARCH: 'SET_SEARCH',
};

export default types;
